name: "SunPy"
description: "Python for Solar Physics"

url: "http://sunpy.github.io/"
#url: "http://localhost:4000/"

paginate: 5
paginate_path: "blog/page:num"
timezone: "America/New_York"

exclude:          [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "less"]

markdown: kramdown
permalink: pretty


authors:
   Cadair:
      display_name: "Stuart Mumford"
      github: "https://github.com/Cadair"
       
   dpshelio:
      display_name: David Pérez-Suárez
      github: "https://github.com/dpshelio"
   
   wafels:
      display_name: Jack Ireland
      github: "https://github.com/wafels"
  
# more authors names to be added. Just for testing now



highlighter: rouge

# Custom vars
current_version:  1.0
repo:             https://github.com/sunpy/sunpy

install_instructions: http://docs.sunpy.org/en/stable/guide/installation/

gems: [jekyll-paginate]

