name: "SunPy"
description: "Python for Solar Physics"

url: "http://sunpy.org"

paginate: 5
paginate_path: "blog/page:num"
timezone: "America/New_York"

exclude:          [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "less"]

markdown: kramdown
permalink: pretty

highlighter: rouge

# Custom vars
current_version:  1.0
repo:             https://github.com/sunpy/sunpy

install_instructions: http://docs.sunpy.org/en/stable/guide/installation/

gems: [jekyll-paginate]

