name: "SunPy"
description: "Python for Solar Physics"

url: "http://sunpy.org"

paginate: 5
paginate_path: "blog/page:num"
timezone: "America/New_York"

exclude:          [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "less"]

markdown: kramdown
permalink: pretty

highlighter: rouge


authors:
   Cadair:
      display_name: "Stuart Mumford"
      github: "https://github.com/Cadair"
       
   dpshelio:
      display_name: "David Pérez-Suárez"
      github: "https://github.com/dpshelio"
   
   wafels:
      display_name: "Jack Ireland"
      github: "https://github.com/wafels"
    
   ehsteve:
      display_name: "Steven Christe"
      github: "https://github.com/ehsteve"
   
   Simon:
      display_name: "Simon Liedtke"
      github: "https://github.com/derdon/"
      
   Nabo:
      display_name: "Nabil Freij"
      github: "https://github.com/nabobalis"

# Custom vars
current_version:  1.0
repo:             https://github.com/sunpy/sunpy

install_instructions: http://docs.sunpy.org/en/stable/guide/installation/

gems: [jekyll-paginate]

